// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace netmvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250501144656_InitialReset")]
    partial class InitialReset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("netmvc.Models.MayTinh", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Doanhthu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tenmay")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("dongia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("MayTinh");
                });

            modelBuilder.Entity("netmvc.Models.SuDungMayTinh", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Giobatdau")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Gioketthuc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IDmaytinh")
                        .HasColumnType("int");

                    b.Property<int>("IDnguoidung")
                        .HasColumnType("int");

                    b.Property<string>("thoigian")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("SuDungMayTinh");
                });

            modelBuilder.Entity("netmvc.Models.TaiKhoan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quyen")
                        .HasColumnType("int");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sodu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tendangnhap")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("TaiKhoan");
                });
#pragma warning restore 612, 618
        }
    }
}
